apiVersion: 1

datasources:
  - name: Time Metrics API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://172.19.0.1:8000
    uid: time-api
    isDefault: true
    jsonData:
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer grafana-token"
