services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-api
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
    restart: unless-stopped
    networks:
      - metrics-network

volumes:
  grafana_data:

networks:
  metrics-network:
    external: true